name: OWASP ZAP Scan

 

on:
  push:
    branches:
      - main  # Change this to your default branch name

 

jobs:
  zap_scan:
    runs-on: ubuntu-latest

 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up permissions
        run: |
          sudo chmod -R 777 $(pwd)

 

      - name: Run OWASP ZAP Scan
        run: |
          docker pull ghcr.io/zaproxy/zaproxy:stable
          docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable zap.sh -cmd -autorun /zap/wrk/zap.yaml
          pwd 
          ls -la
          sudo chmod -R 777 /zap/wrk/*

          # Zip the ZAP Report
          zip -j /zap/wrk/zap_report.zip /zap/wrk/2023-08-10-ZAP-Report-dev-bo.nephroplus.com.html

          # Upload Zipped Report as an artifact
          echo "::set-output name=artifact_path::/zap/wrk/zap_report.zip"

      - name: Upload Zipped Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report-zip
          path: ${{ steps.zap_scan.outputs.artifact_path }}
